---
variables:
  DEFAULT-BRANCH: master
trigger:
  - "$(DEFAULT-BRANCH)"
schedules:
  - cron: '30 13 * * 6'
    displayName: 'build on weekly'
    branches:
      include:
        - "$(DEFAULT-BRANCH)"
parameters:
  - name: jdkversion
    displayName: java version
    type: string
    default: '1.8'
    values:
      - '1.17'
      - '1.11'
      - '1.10'
      - '1.8'
      - '1.9'
pool:
  vmImage: ubuntu-22.04
stages:
  - stage: build
    displayName: 'build using maven'
    jobs:
      - job: build
        displayName: maven build
        steps:
        - task: 'Maven@4'
          inputs:
            mavenPOMFile: 'pom.xml'
            goals: 'clean package'
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: ${{ parameters.jdkversion }}
        - task: CopyFiles@2
          inputs:
            contents: '**/*.war'
            targetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: GameOfLife