---
variables:
  DEFAULT-BRANCH: master
trigger:
  - "$(DEFAULT-BRANCH)"
schedules:
  - cron: '30 13 * * 6'
    displayName: 'build on weekly'
    branches:
      include:
        - "$(DEFAULT-BRANCH)"
parameters:
  - name: jdkversion
    displayName: java version
    type: string
    default: '1.8'
    values:
      - '1.17'
      - '1.11'
      - '1.10'
      - '1.8'
      - '1.9'
pool:
  vmImage: ubuntu-22.04
stages:
  -template: templates/build-stage-gol.yml
  