---
variables:
  DEFAULT-BRANCH: master
trigger:
  - "$(DEFAULT-BRANCH)"
schedules:
  - cron: '30 13 * * 6'
    displayName: 'build on weekly'
    branches:
      include:
        - "$(DEFAULT-BRANCH)"
pool:
  vmImage: ubuntu-22.04
stages:
  - template: templates/build-stage-gol.yml
    parameters:
      jdkversion: '1.8'
      archievefilepattern: "**/*.war"
   
  