---
variables:
  - group: spring-petclinic
trigger:
  - "$(DEFAULT-BRANCH)"
schedules:
  - cron: '30 13 * * 6'
    displayName: 'build on weekly'
    branches:
      include:
        - "$(DEFAULT-BRANCH)"
pool:
  vmImage: ubuntu-22.04
resources:
  repositories:
    - repository: templates
      type: git
      ref: main
      name: tempoutside
stages:
  - template: tempoutside/maven-build.yml@templates
    parameters:
      jdkversion: '1.17'
      archievefilepattern: "**/spring-petclinic*.jar"
     
        