---
trigger:
  - main
schedules:
  - cron: '30 13 * * 6'
    displayName: 'build on weekly'
    branches:
      include:
        - main
parameters:
  - name: jdkversion
    displayName: java version
    type: string
    default: '1.17'
    values:
      - '1.17'
      - '1.11'
      - '1.10'
      - '1.8'
      - '1.9'

pool:
  vmImage: ubuntu-22.04
stages:
  - stage: build
    displayName: 'build using maven'
    jobs:
      - job: build
        displayName: maven build
        steps:
        - task: 'Maven@4'
          inputs:
            mavenPOMFile: 'pom.xml'
            goals: 'clean package'
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'